- name: "Change the hostname to {{hostname}}"
  win_hostname:
    name: "{{hostname}}"
  register: win_hostname

- name: Reboot if needed
  win_reboot:
    reboot_timeout: 600
    post_reboot_delay: 100
  when: win_hostname.reboot_required

- name: "Add workstation to {{domain_name}}"
  win_domain_membership:
    dns_domain_name: "{{domain_name}}"
    domain_admin_user: "Administrator@{{domain_name}}"
    domain_admin_password: "{{password}}"
    domain_ou_path: "{{domain_ou_path}}"
    state: domain
  register: domain_state

- name: Reboot if needed
  win_reboot:    
    reboot_timeout: 600
    post_reboot_delay: 100
  when: domain_state.reboot_required

