---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

- name: "Setup vulnerabilities with tasks"
  hosts: dc01,dc02,dc03,srv02,srv03
  tasks:
    - include_role:
        name: "vulns/{{item}}"
      loop: "{{lab.hosts[dict_key].vulns}}"
    - include_role:
        name: "ps"
      vars:
        script_path: "../ad/{{domain_name}}/scripts"
        ps_script: "{{script_path}}/{{item}}"
      loop: "{{lab.hosts[dict_key].scripts}}"
